version: '3'

services:
    app:
        build: .
        container_name: app
        entrypoint: dockerize -template ./.docker/php/env.tmpl:./.env -wait tcp://db:3306 -timeout 60s ./.docker/entrypoint.sh
        ports:
            - "9000"
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        networks:
            - app-network
    nginx:
        build: ./.docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/database/dumps:/dumps:rw,cached
            - ./.docker/database/data:/var/lib/mysql:rw,cached
            - ./.docker/database/config:/etc/mysql/conf.d:rw,cached
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network
    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
